esphome:
  name: bms-libprotocol-handler
  includes:
    - component/sdragos_mppsolar/BMSLibProtocolUARTHandler.cpp
    - component/sdragos_mppsolar/BMSLibProtocolUARTHandler.h
    - component/sdragos_mppsolar/BMSLibProtocolDataAdapter.h
    - component/sdragos_mppsolar/BMSLibProtocolMockDataAdapter.h

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y

# Enable Home Assistant API
api:
  encryption:
    key: !secret home_assistant_api_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_fallback_ssid
    password: !secret wifi_fallback_password

logger:

uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  stop_bits: 1

custom_component:
- lambda: |-
    auto my_custom = new sdragos::mppsolar::BMSLibProtocolUARTHandler(id(uart_bus));
    auto dataAdapter = new sdragos::mppsolar::BMSLibProtocolMockDataAdapter();
    my_custom->setDataAdapter(dataAdapter);
    return {my_custom};